# Form implementation generated from reading ui file 'hdsd.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 470)
        self.labelImg = QtWidgets.QLabel(parent=Form)
        self.labelImg.setGeometry(QtCore.QRect(0, 0, 750, 470))
        self.labelImg.setText("")
        self.labelImg.setObjectName("labelImg")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(650, 380, 81, 81))
        self.pushButton.setStyleSheet("font: 72pt \"Arial\";\n"
"border: 0px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 380, 81, 81))
        self.pushButton_2.setStyleSheet("font: 72pt \"Arial\";\n"
"border: 0px;")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", ">"))
        self.pushButton_2.setText(_translate("Form", "<"))
