# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Studious):
        Studious.setObjectName("Studious")
        Studious.setGeometry(QtCore.QRect(0, 0, 800, 514))
        self.centralwidget = QtWidgets.QWidget(parent=Studious)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 170, 341, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Studious.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Studious)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        Studious.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Studious)
        self.statusbar.setObjectName("statusbar")
        Studious.setStatusBar(self.statusbar)

        self.retranslateUi(Studious)
        QtCore.QMetaObject.connectSlotsByName(Studious)

    def retranslateUi(self, Studious):
        _translate = QtCore.QCoreApplication.translate
        Studious.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "UR GAY"))
