# Form implementation generated from reading ui file 'pinDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QDialog):
    def setupUi(self, Dialog):
        Dialog.setFixedSize(480, 88)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assert/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet('''* {background-color: rgb(33, 37, 43);color: rgb(249, 245, 246);font: 20pt \"Arial\";}
QLabel{qproperty-alignment: \'AlignCenter\';qproperty-margin: auto;}
''')
        self.lb_task = QtWidgets.QLabel(parent=Dialog)
        self.lb_task.setGeometry(QtCore.QRect(0, -2, 240, 96))
        self.lb_task.setObjectName("lb_task")
        self.lb_time = QtWidgets.QLabel(parent=Dialog)
        self.lb_time.setGeometry(QtCore.QRect(240, -2, 240, 96))
        self.lb_time.setObjectName("lb_time")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Studious - Pin Task"))
